### ISSUE TITLE
RTP Forwarding Plugin on cloud instance

### ISSUE THREAD

**Issue by saiakhil19932** [michaelfranzl/janus-rtpforward-plugin#7] opened 2021-02-11 18:53 UTC
Greetings,
Thanks for this amazing plugin and demo provided.

I was successfully able to do my task in my local using this plugin.

 **Issue**:
My build details:
1. Janus - 0.9.2
2. Janus - rtp forwarding plugin - 0.9.2
3. Ubuntu 18.04-only cli on OCI instance 

When i deployed Janus and the rtp_forwarding_plugin on my instance and tried to execute the demo, it is failing and the error i get is this ,

**rtpforward Negotiated video codec is VP8
[WARN] [521897937773695] ICE failed for component 1 in stream 1, but let's give it some time... (trickle received, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1720] [521897937773695] ICE failed for component 1 in stream 1...
rtpforward hangup media.**

I got the same error when executing demo's shipped with janus-gateway but i resolved it by adding "nat_1_1 = "public_ip" in janus.jcfg then everything worked fine and currently after compiling along with janus_rtpforward_plugin the demos provided by janus-gateway works fine without any errors but demo provided by janus-rtpforward-plugin does not work because of the above error.

Is there a way to add nat_1_1 = "public_ip" in this plugin?

**Comment by michaelfranzl** [comment] 2021-02-12 15:22
I don't think that the plugin is the correct place to add a setting like this. The plugin doesn't do anything related to NAT.

**Comment by saiakhil19932** [comment] 2021-02-15 02:20
Is there any possible solution for the above error?

**Comment by michaelfranzl** [comment] 2021-02-17 14:33
I don't know. Probably. From a quick survey of this error in various forums, it doesn't seem to be an issue with Janus, but with the details of the deployment.

I'm closing this issue because it's unlikely to be related to janus-rtpforward-plugin.

If you can reproduce your issue using https://github.com/michaelfranzl/vagrant_janus-rtpforward-plugin_demo, then we can re-open this issue.

**Closed as completed by michaelfranzl** 2021-02-17 14:33 UTC
